name: Sources release
on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Produce artifacts
      run: ./artifacts.sh Sources
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: sources-release
        path: artifacts/
        retention-days: 5
