name: Linux build Debug
on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: build-dep
      run: ./get --build-dep ${{env.BUILD_CONFIGURATION}}
     
    - name: install sdl3 system-wide
      run: sudo dpkg -i lib/platform/sdl3-deb/libsdl3-*.deb || true; sudo apt install -f

    - name: configure
      run: ./configure
      
    - name: make
      run: make -j BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

  # - name: make check
  #   run: make check
  # - name: make distcheck
  #   run: make distcheck

    - name: Produce artifacts
      run: ./artifacts.sh ${{env.BUILD_CONFIGURATION}}
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-${{env.BUILD_CONFIGURATION}}
        path: artifacts/
        retention-days: 5
